spring:
  profiles:
    active: dev # Set the active profile to dev by default (can be overridden)
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      auto-commit: true

  security:
    user:
      name: ${loginUser}
      password: ${loginPassword}

  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# Common configuration (shared across environments)
pdf:
  output:
    path: output/qrcodes.pdf

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: j.rodriguez0506071412@gmail.com
  password: tamy rvyl pgwh ggkc #${EMAIL_PASSWORD}
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true

web:
  resources:
    static-locations: classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/
    cache:
      cachecontrol:
        max-age: 3600 # Cache static resources in the client for 1 hour.
        public: true   # Mark them as publicly cacheable.

# Server-related configurations
server:
  servlet:
    context-path: /   # Ensures that your app serves static files correctly without a sub-path.
