spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      platform: org.postgresql.Driver
# Optional: any production-specific overrides can go here
pdf:
  output:
    path: /var/app/output/qrcodes.pdf
